name: C/C++ CI

on:
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Add all repos
      run: |
        sudo bash -c 'cat > /etc/apt/sources.list << EOF
        deb [arch=arm64] http://ports.ubuntu.com/ noble main restricted universe multiverse
        deb [arch=arm64] http://ports.ubuntu.com/ noble-security main restricted universe multiverse
        deb [arch=arm64] http://ports.ubuntu.com/ noble-updates main restricted universe multiverse
        deb [arch=arm64] http://ports.ubuntu.com/ noble-backports main restricted universe multiverse
        deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble main restricted
        deb-src http://archive.ubuntu.com/ubuntu/ noble main restricted
        deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-updates main restricted
        deb-src http://archive.ubuntu.com/ubuntu/ noble-updates main restricted
        deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble universe
        deb-src http://archive.ubuntu.com/ubuntu/ noble universe
        deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-updates universe
        deb-src http://archive.ubuntu.com/ubuntu/ noble-updates universe
        deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble multiverse
        deb-src http://archive.ubuntu.com/ubuntu/ noble multiverse
        deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-updates multiverse
        deb-src http://archive.ubuntu.com/ubuntu/ noble-updates multiverse
        deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse
        deb-src http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse
        deb [arch=amd64] http://security.ubuntu.com/ubuntu noble-security main restricted
        deb-src http://security.ubuntu.com/ubuntu noble-security main restricted
        deb [arch=amd64] http://security.ubuntu.com/ubuntu noble-security universe
        deb-src http://security.ubuntu.com/ubuntu noble-security universe
        deb [arch=amd64] http://security.ubuntu.com/ubuntu noble-security multiverse
        deb-src http://security.ubuntu.com/ubuntu noble-security multiverse
        EOF'
        sudo rm -r -f /etc/apt/sources.list.d;
        sudo apt clean;
        sudo apt update;
    - uses: actions/checkout@v4
    - name: Static build for x86_64
      run: make fresh STATIC=1
    - name: Rename for x86_64
      run: mv ampart ampart-x86_64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: static-build
        path: ampart-*
        if-no-files-found: error
        retention-days: 90
    - name: Clear
      run: make clean; sudo apt update; sudo apt autoremove; sudo apt dist-upgrade
      continue-on-error: true
    - name: Install cross toolchain for aarch64
      continue-on-error: true
      run: |
        # cat /etc/apt/sources.list.d/ubuntu.sources
        # sudo bash -c "echo -e '\
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble main restricted\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-updates main restricted\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble universe\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-updates universe\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble multiverse\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-updates multiverse\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-backports main restricted universe multiverse\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-security main restricted\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-security universe\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-security multiverse\n' > /etc/apt/sources.list.d/arm64-cross.list"
        # cat /etc/apt/sources.list.d/ubuntu.sources
        sudo dpkg --add-architecture arm64 || true;
        sudo apt-get update
        sudo apt-get install \
          g++-aarch64-linux-gnu \ 
          gcc-aarch64-linux-gnu \
          binutils-aarch64-linux-gnu \
          linux-libc-dev:arm64 \
          zlib1g-dev:arm64
    - name: Static build for aarch64
      run: make fresh CC=aarch64-linux-gnu-gcc STRIP=aarch64-linux-gnu-strip STATIC=1
    - name: Rename for aarch64
      run: mv ampart ampart-aarch64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: static-build
        path: ampart-*
        if-no-files-found: error
        retention-days: 90
