name: C/C++ CI

on:
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Static build for x86_64
      run: make fresh STATIC=1
    - name: Rename for x86_64
      run: mv ampart ampart-x86_64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: static-build
        path: ampart-*
        if-no-files-found: error
        retention-days: 90
    - name: Clear
      run: make clean; sudo apt update; sudo apt autoremove; sudo apt dist-upgrade
      continue-on-error: true
    - name: Install cross toolchain for aarch64
      continue-on-error: true
      run: |
        sudo dpkg --add-architecture arm64
        sudo bash -c "echo -e '\
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble main restricted\n
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-updates main restricted\n
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble universe\n
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-updates universe\n
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble multiverse\n
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-updates multiverse\n
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-backports main restricted universe multiverse\n
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-security main restricted\n
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-security universe\n
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-security multiverse\n' > /etc/apt/sources.list.d/arm64-cross.list"
        cat /etc/apt/sources.list.d/ubuntu.sources
        sudo apt-get update
        sudo apt-get install \
          g++-aarch64-linux-gnu-g++ \ 
          gcc-aarch64-linux-gnu \
          binutils-aarch64-linux-gnu \
          linux-libc-dev:arm64 \
          zlib1g-dev:arm64
    - name: Static build for aarch64
      run: make fresh CC=aarch64-linux-gnu-gcc STRIP=aarch64-linux-gnu-strip STATIC=1
    - name: Rename for aarch64
      run: mv ampart ampart-aarch64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: static-build
        path: ampart-*
        if-no-files-found: error
        retention-days: 90
