name: C/C++ CI

on:
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Add all repos
      run: |
        sudo bash -c "echo -e '\
          # sources.list file for arm cross-development under amd64
          deb [arch=arm64] http://ports.ubuntu.com/ noble main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ noble-security main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ noble-updates main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ noble-backports main restricted universe multiverse
          
          # See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
          # newer versions of the distribution.
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble main restricted
          deb-src http://archive.ubuntu.com/ubuntu/ noble main restricted
          
          ## Major bug fix updates produced after the final release of the
          ## distribution.
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-updates main restricted
          deb-src http://archive.ubuntu.com/ubuntu/ noble-updates main restricted
          
          ## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
          ## team. Also, please note that software in universe WILL NOT receive any
          ## review or updates from the Ubuntu security team.
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble universe
          deb-src http://archive.ubuntu.com/ubuntu/ noble universe
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-updates universe
          deb-src http://archive.ubuntu.com/ubuntu/ noble-updates universe
          
          ## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
          ## team, and may not be under a free licence. Please satisfy yourself as to 
          ## your rights to use the software. Also, please note that software in 
          ## multiverse WILL NOT receive any review or updates from the Ubuntu
          ## security team.
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble multiverse
          deb-src http://archive.ubuntu.com/ubuntu/ noble multiverse
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-updates multiverse
          deb-src http://archive.ubuntu.com/ubuntu/ noble-updates multiverse
          
          ## N.B. software from this repository may not have been tested as
          ## extensively as that contained in the main release, although it includes
          ## newer versions of some applications which may provide useful features.
          ## Also, please note that software in backports WILL NOT receive any review
          ## or updates from the Ubuntu security team.
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse
          deb-src http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse
          
          deb [arch=amd64] http://security.ubuntu.com/ubuntu noble-security main restricted
          deb-src http://security.ubuntu.com/ubuntu noble-security main restricted
          deb [arch=amd64] http://security.ubuntu.com/ubuntu noble-security universe
          deb-src http://security.ubuntu.com/ubuntu noble-security universe
          deb [arch=amd64] http://security.ubuntu.com/ubuntu noble-security multiverse
          deb-src http://security.ubuntu.com/ubuntu noble-security multiverse
          
          ## Uncomment the following two lines to add software from Canonical's
          ## 'partner' repository.
          ## This software is not part of Ubuntu, but is offered by Canonical and the
          ## respective vendors as a service to Ubuntu users.
          # deb [arch=amd64] http://archive.canonical.com/ubuntu noble partner
          # deb-src http://archive.canonical.com/ubuntu noble partner
          
          ## This software is not part of Ubuntu, but is offered by third-party
          ## developers who want to ship their latest software.
          deb [arch=amd64] http://extras.ubuntu.com/ubuntu noble main
          deb-src http://extras.ubuntu.com/ubuntu noble main\n' > /etc/apt/sources.list"
        rm -r -f /etc/apt/sources.list.d;
        apt clean;
        apt update;
        apt dist-upgrade;
    - uses: actions/checkout@v4
    - name: Static build for x86_64
      run: make fresh STATIC=1
    - name: Rename for x86_64
      run: mv ampart ampart-x86_64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: static-build
        path: ampart-*
        if-no-files-found: error
        retention-days: 90
    - name: Clear
      run: make clean; sudo apt update; sudo apt autoremove; sudo apt dist-upgrade
      continue-on-error: true
    - name: Install cross toolchain for aarch64
      continue-on-error: true
      run: |
        # cat /etc/apt/sources.list.d/ubuntu.sources
        # sudo bash -c "echo -e '\
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble main restricted\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-updates main restricted\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble universe\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-updates universe\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble multiverse\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-updates multiverse\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-backports main restricted universe multiverse\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-security main restricted\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-security universe\n
        #   deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports noble-security multiverse\n' > /etc/apt/sources.list.d/arm64-cross.list"
        # cat /etc/apt/sources.list.d/ubuntu.sources
        sudo dpkg --add-architecture arm64 || true;
        sudo apt-get update
        sudo apt-get install \
          g++-aarch64-linux-gnu-g++ \ 
          gcc-aarch64-linux-gnu \
          binutils-aarch64-linux-gnu \
          linux-libc-dev:arm64 \
          zlib1g-dev:arm64
    - name: Static build for aarch64
      run: make fresh CC=aarch64-linux-gnu-gcc STRIP=aarch64-linux-gnu-strip STATIC=1
    - name: Rename for aarch64
      run: mv ampart ampart-aarch64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: static-build
        path: ampart-*
        if-no-files-found: error
        retention-days: 90
